### ISSUE TITLE
doesent work when unfocused anymore

### ISSUE THREAD

**Issue by clumsyfingers** [anomalyce/twitter-idle-autorefresh#1] opened 2019-08-26 20:13 UTC
it doesent work for me anymore when unfocussed. ive set it to refresh both when focused and unfocused. also tried with just unfocused. nothing happens. when focused it works though

**Comment by anomalyce** [comment] 2019-09-13 09:19
Hey.

Apologies for not getting back sooner, I haven't received a notification for whatever reason.

I have just pushed a couple of fixes, including one for an issue where the "both focused/unfocused" state wouldn't enable the add-on. I'm just about to publish it on the AMO, and once Mozilla has approved of the changes, maybe you could give it another go (v1.1.2).

If you're still experiencing issues after that, please let me know.

Again, apologies for the late response and thanks for giving the add-on a go!

**UPDATE:** Mozilla approved the update pretty much instantly, so you should be able to update the add-on right away.

**Comment by clumsyfingers** [comment] 2019-09-14 08:21
thanks
does this only work when set to 'home' ? i always use 'latest tweets' and it doesent autorefresh unless focused

**Comment by anomalyce** [comment] 2019-09-14 11:07
It's only available on the home feed at the moment, yes, but whether you sort by latest tweets or their top tweets shouldn't matter. I personally use latest tweets as well.

What version of Firefox are you using? and on what operating system?

Could you possibly also enable the "Output console logs" within the debugging section of the add-on's preferences, & open the console (Ctrl + Shift + K, or Cmd + Opt + K if on macOS). Then type `Twitter Idle AutoRefresh` into the Filter output field in order to remove any non-add-on related logs and then paste them here, please?

Before you paste them, please make sure you have triggered the issue (it not autorefreshing, that is) at least once.

Thanks!

**Comment by clumsyfingers** [comment] 2019-09-14 16:08
hi
in on solus linux and im using waterfox 56.2.14 (64-bit)
theres no option to enable output console logs see https://i.imgur.com/FyNOPZz.png
might be cos in not using firefox proper?

**Comment by anomalyce** [comment] 2019-09-14 17:50
Hi again.

I'm using Waterfox 68 myself, and it works fine there, might be some incompatibilities with the code and version 56. I'll download Waterfox 56 during next week and see if I can find out what the cause might be.

**Comment by anomalyce** [comment] 2019-09-18 14:25
Okay, small update, I think I've found the issue and have applied a fix for it. It's currently in the process of being approved by Mozilla. Usually they're pretty quick, but may take a few hours.

If you're impatient, you may download v1.1.3 from this repository, and enable it manually through `about:debugging`.

I'll close this issue as I consider it fixed for now, but if it the issue remains, please re-open the issue and I'll take another look.

PS. If at first it doesn't work, try completely reinstalling the add-on before re-opening the issue.

**UPDATE:** Once again, Mozilla were blazing fast and published it as I was typing this response. No need to manually install it through `about:debugging`.

**Comment by clumsyfingers** [comment] 2019-09-18 20:08
thanks for your work, but it STILL doesent work when unfocused. i think maybe ill make a fresh profile and see how it goes. in the meantime ive found tweetdeck to be pretty ok

**Comment by anomalyce** [comment] 2019-09-18 20:19
I'm more than happy to continue trying to find a solution to the issue if you would prefer to use my add-on over TweetDeck. Either way is fine by me :-)

If you haven't already made a blank profile, could you try going into the add-on preferences, and just save once? see if that makes any difference.

**Comment by clumsyfingers** [comment] 2019-09-19 14:53
seems to work in a new profile. i dont know what caused it, might have been one of the multitude of addons and scripts i used to make the new twitter be more like the old

i used the save button in the addon prefs many times in the old profile but it didnt make a difference

anyway, thanks, the addon is a must!

**Comment by anomalyce** [comment] 2019-09-19 15:10
Ah, yeah, the mysterious & whacky side of development :-) so many things that can collide. Happy you managed to fix it with a new profile though!

Please let me know if any other issues occur. Hopefully I'll have some spare time sometime soon to develop the other feeds besides the home feed too.

**Closed as completed by anomalyce** 2019-09-19 15:10 UTC

**Comment by clumsyfingers** [comment] 2019-09-19 15:50
it doesent seem to update the time stamps every 15 seconds when there arent new tweets though. might be a twitter thing. the old twitter was way better

**Comment by clumsyfingers** [comment] 2019-09-19 16:02
hmm i may have found the problem, i also had https://addons.mozilla.org/en-US/firefox/addon/twitter-autoload/ installed, although disabled. tested it again now, with both installed neither work, even if one is disabled

**Comment by anomalyce** [comment] 2019-09-19 16:57
Yeah, think the new Twitter design requires the user to have focus on the browser tab in order for updates to occur. The way my add-on circumvents this is by running a loop that checks every 15 (or whatever you've picked) seconds and simulates the user pressing on the Home icon, which in turn forces Twitter to display any new tweets.

So the timestamps will most likely not update so long as the page remains unfocused.

As far as the issue with the other add-on goes, that's odd, but glad you sorted it. Appreciate that you decided to share what may be the cause to the root issue!
