### ISSUE TITLE
Looks like Twitter changed things up slightly, but I found a fix for you

### ISSUE THREAD

**Issue by JBlitzen** [anomalyce/twitter-idle-autorefresh#2] opened 2021-03-25 22:17 UTC
Clicking the Home button refreshes the feed, and it has a simple querySelector to replace the older one you were using.

So changing line 5 in your content.js to "get RefreshSelector() { return 'nav > a > div' }" seems to work fine, I've tested it locally.

I'd do a pull request but I'm a little fuzzy on how to do that.

**Comment by anomalyce** [comment] 2021-03-25 22:20
Oh, thank you for reporting this, I hadn't noticed yet! I'll be able to take a look tomorrow evening or Saturday possibly, but feel free to try your way with a PR if you want to learn. I don't mind if it gets messy!

**Comment by 9niine** [comment] 2021-03-26 18:44
> 
> 
> Oh, thank you for reporting this, I hadn't noticed yet! I'll be able to take a look tomorrow evening or Saturday possibly, but feel free to try your way with a PR if you want to learn. I don't mind if it gets messy!

I am sorry to bother you, but i have been using this addon so long and i absolutely need it,thank you for creating this addon, 
and  like what JBlitzen said i also found it not working as well, i dun know how about codes but i manage to edit the file locally , and how can i apply it into firefox? Again thank you.

**Comment by anomalyce** [comment] 2021-03-26 18:56
No bother whatsoever! Glad my addon can provide some use for you! I'm working on the fix as we speak, also adding the ability to change the selectors through the addon's preferences should something similar happen in the future before I can get to it. Once it's all done, I'll upload it to the AMO. It might take a few hours (or days) for Mozilla to approve the update however.

If you can't wait that long however, you can always go to `about:debugging` and click on `This Firefox` in the sidebar. Click the `Load Temporary Add-on...` button and select the addon's manifest.json file. I recommend removing it once the new update is available though to make sure you get any future updates.

**Comment by 9niine** [comment] 2021-03-26 19:20
> No bother whatsoever! Glad my addon can provide some use for you! I'm working on the fix as we speak, also adding the ability to change the selectors through the addon's preferences should something similar happen in the future before I can get to it. Once it's all done, I'll upload it to the AMO. It might take a few hours (or days) for Mozilla to approve the update however.
> 
> If you can't wait that long however, you can always go to `about:debugging` and click on `This Firefox` in the sidebar. Click the `Load Temporary Add-on...` button and select the addon's manifest.json file. I recommend removing it once the new update is available though to make sure you get any future updates.

THANK YOU SO MUCH ! this auto refresh addon means alot to me cuz i bought a monitor almost is just for checking twitter while working and gaming... And i also tried Temporary Add-on and it works perfecty , this is the first time i learn things realted to making addons and codes , it was a very new experience for me and thank you so much again! appreciate!

**Comment by anomalyce** [comment] 2021-03-26 19:23
Okay, I uploaded an updated version (v1.2.0) to the AMO a few minutes ago and Mozilla have already approved it! 🥳

https://addons.mozilla.org/en-US/firefox/addon/twitter-idle-autorefresh/versions/

Please let me know if you experience any issues with the updated version and thanks for letting me know in the first place.

Have a good weekend!

> THANK YOU SO MUCH ! this auto refresh addon means alot to me cuz i bought a monitor almost is just for checking twitter while working and gaming... And i also tried Temporary Add-on and it works perfecty , this is the first time i learn things realted to making addons and codes , it was a very new experience for me and thank you so much again! appreciate!

🥳 🥳 Glad you like it and hopefully the updated version works just as well! If not, you have the option to now edit the selectors directly from the add-on preferences.

**Comment by JBlitzen** [comment] 2021-03-26 20:14
The 1.2 version doesn't seem to be working for me.  My local version still does; where I think the only change was that one line for the RefreshSelector declaration in content.js, but I'm not positive.  Attached should be a zip with what I added as a debug addon and is working great:

[twitter-idle-autorefresh-930e41b54cf21e8f726311f9fe382ce12b9bb437 - UPDATE.zip](https://github.com/anomalyce/twitter-idle-autorefresh/files/6214144/twitter-idle-autorefresh-930e41b54cf21e8f726311f9fe382ce12b9bb437.-.UPDATE.zip)

(Sorry again that I can't figure out pull requests this week; I'm rebuilding a data center.  But having twitter refreshing on a monitor is nice company while I'm working on that.)

**Comment by anomalyce** [comment] 2021-03-26 20:16
Yeah, I noticed that myself and am currently debugging the issue. Don't worry about the PR & good luck rebuilding the data center! I made a few more changes than just the selector, but the selector isn't the problem, something is causing the add-on not to run at all. I'm looking for a fix and will update you all here when I've submitted a new version.

Sorry for the inconvenience!

**Comment by anomalyce** [comment] 2021-03-26 20:57
Okay I have found a fix and am submitting it to the AMO as I type this. Sorry again for the inconvenience, but it should all work with the latest version (v1.2.1) as soon as Mozilla approves it.

It was caused by the way the add-on was loading the preferences after Twitter had properly loaded, but that also meant that it couldn't fetch the selector for the feed. Catch 22. I've now re-structured the add-on to first load the options, and then check if Twitter has properly loaded before continuing on with the rest of the add-on functionality.

Let's hope!

**Comment by anomalyce** [comment] 2021-03-26 21:03
I'll close this issue again seing as Mozilla has now approved the new version, but please feel free to comment again should you notice any more issues. Hoping it's all smooth sailing from here on forth though. Thanks again for both of your reports & input!

Have a good weekend.

**Closed as completed by anomalyce** 2021-03-26 21:03 UTC
